import { type NextRequest, NextResponse } from "next/server";
import spotifyApi from "../../lib/spotify";

export async function POST(request: NextRequest) {
  const accessToken = request.cookies.get("spotify_access_token")?.value;
  const refreshToken = request.cookies.get("spotify_refresh_token")?.value;

  if (!accessToken) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  }

  try {
    const body = await request.json();
    const { name, description, trackUris } = body;

    if (!name || !trackUris || trackUris.length === 0) {
      return NextResponse.json(
        { error: "Invalid playlist data" },
        { status: 400 },
      );
    }

    spotifyApi.setAccessToken(accessToken);
    if (refreshToken) {
      spotifyApi.setRefreshToken(refreshToken);
    }

    const me = await spotifyApi.getMe();
    const userId = me.body.id;

    const playlist = (await spotifyApi.createPlaylist(userId, {
      name,
      description: description || "Generated by AI",
      public: false,
    } as any)) as any;

    await spotifyApi.addTracksToPlaylist(playlist.body.id, trackUris);

    return NextResponse.json({
      playlistId: playlist.body.id,
      playlistUrl: playlist.body.external_urls.spotify,
      playlistName: playlist.body.name,
    });
  } catch (error: unknown) {
    console.error("Error creating playlist:", error);

    if (
      error &&
      typeof error === "object" &&
      "statusCode" in error &&
      error.statusCode === 401
    ) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    return NextResponse.json(
      { error: "Failed to create playlist" },
      { status: 500 },
    );
  }
}
